# -------------------------------------------------
# Project created by QtCreator 2013-08-19T11:08:15
# -------------------------------------------------
QMAKE_CXXFLAGS += -msse \
    -msse2 \
    -mmmx
TARGET = shuriken
TEMPLATE = app
SOURCES += src/JuceLibraryCode/modules/juce_audio_basics/juce_audio_basics.cpp \
    src/JuceLibraryCode/modules/juce_audio_basics/buffers/juce_FloatVectorOperations.cpp \
    src/JuceLibraryCode/modules/juce_audio_basics/buffers/juce_AudioSampleBuffer.cpp \
    src/JuceLibraryCode/modules/juce_audio_basics/buffers/juce_AudioDataConverters.cpp \
    src/JuceLibraryCode/modules/juce_audio_basics/effects/juce_LagrangeInterpolator.cpp \
    src/JuceLibraryCode/modules/juce_audio_basics/effects/juce_IIRFilter.cpp \
    src/JuceLibraryCode/modules/juce_audio_basics/midi/juce_MidiMessageSequence.cpp \
    src/JuceLibraryCode/modules/juce_audio_basics/midi/juce_MidiMessage.cpp \
    src/JuceLibraryCode/modules/juce_audio_basics/midi/juce_MidiKeyboardState.cpp \
    src/JuceLibraryCode/modules/juce_audio_basics/midi/juce_MidiFile.cpp \
    src/JuceLibraryCode/modules/juce_audio_basics/midi/juce_MidiBuffer.cpp \
    src/JuceLibraryCode/modules/juce_audio_basics/sources/juce_ToneGeneratorAudioSource.cpp \
    src/JuceLibraryCode/modules/juce_audio_basics/sources/juce_ReverbAudioSource.cpp \
    src/JuceLibraryCode/modules/juce_audio_basics/sources/juce_ResamplingAudioSource.cpp \
    src/JuceLibraryCode/modules/juce_audio_basics/sources/juce_MixerAudioSource.cpp \
    src/JuceLibraryCode/modules/juce_audio_basics/sources/juce_IIRFilterAudioSource.cpp \
    src/JuceLibraryCode/modules/juce_audio_basics/sources/juce_ChannelRemappingAudioSource.cpp \
    src/JuceLibraryCode/modules/juce_audio_basics/sources/juce_BufferingAudioSource.cpp \
    src/JuceLibraryCode/modules/juce_audio_basics/synthesisers/juce_Synthesiser.cpp \
    src/JuceLibraryCode/modules/juce_audio_devices/juce_audio_devices.cpp \
    src/JuceLibraryCode/modules/juce_audio_devices/audio_cd/juce_AudioCDReader.cpp \
    src/JuceLibraryCode/modules/juce_audio_devices/audio_io/juce_AudioIODeviceType.cpp \
    src/JuceLibraryCode/modules/juce_audio_devices/audio_io/juce_AudioIODevice.cpp \
    src/JuceLibraryCode/modules/juce_audio_devices/audio_io/juce_AudioDeviceManager.cpp \
    src/JuceLibraryCode/modules/juce_audio_devices/midi_io/juce_MidiOutput.cpp \
    src/JuceLibraryCode/modules/juce_audio_devices/midi_io/juce_MidiMessageCollector.cpp \
    src/JuceLibraryCode/modules/juce_audio_devices/native/juce_win32_WASAPI.cpp \
    src/JuceLibraryCode/modules/juce_audio_devices/native/juce_win32_Midi.cpp \
    src/JuceLibraryCode/modules/juce_audio_devices/native/juce_win32_DirectSound.cpp \
    src/JuceLibraryCode/modules/juce_audio_devices/native/juce_win32_AudioCDReader.cpp \
    src/JuceLibraryCode/modules/juce_audio_devices/native/juce_win32_AudioCDBurner.cpp \
    src/JuceLibraryCode/modules/juce_audio_devices/native/juce_win32_ASIO.cpp \
    src/JuceLibraryCode/modules/juce_audio_devices/native/juce_mac_CoreMidi.cpp \
    src/JuceLibraryCode/modules/juce_audio_devices/native/juce_mac_CoreAudio.cpp \
    src/JuceLibraryCode/modules/juce_audio_devices/native/juce_linux_Midi.cpp \
    src/JuceLibraryCode/modules/juce_audio_devices/native/juce_linux_JackAudio.cpp \
    src/JuceLibraryCode/modules/juce_audio_devices/native/juce_linux_AudioCDReader.cpp \
    src/JuceLibraryCode/modules/juce_audio_devices/native/juce_linux_ALSA.cpp \
    src/JuceLibraryCode/modules/juce_audio_devices/native/juce_ios_Audio.cpp \
    src/JuceLibraryCode/modules/juce_audio_devices/native/juce_android_OpenSL.cpp \
    src/JuceLibraryCode/modules/juce_audio_devices/native/juce_android_Midi.cpp \
    src/JuceLibraryCode/modules/juce_audio_devices/native/juce_android_Audio.cpp \
    src/JuceLibraryCode/modules/juce_audio_devices/sources/juce_AudioTransportSource.cpp \
    src/JuceLibraryCode/modules/juce_audio_devices/sources/juce_AudioSourcePlayer.cpp \
    src/JuceLibraryCode/modules/juce_audio_formats/juce_audio_formats.cpp \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/juce_WindowsMediaAudioFormat.cpp \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/juce_WavAudioFormat.cpp \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/juce_QuickTimeAudioFormat.cpp \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/juce_OggVorbisAudioFormat.cpp \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/juce_MP3AudioFormat.cpp \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/juce_LAMEEncoderAudioFormat.cpp \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/juce_FlacAudioFormat.cpp \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/juce_CoreAudioFormat.cpp \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/juce_AiffAudioFormat.cpp \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/window_flac.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/stream_encoder_framing.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/stream_encoder.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/stream_decoder.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/memory.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/md5.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/lpc_flac.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/format.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/float.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/fixed.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/crc.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/cpu.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/bitwriter.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/bitreader.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/bitmath.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/framing.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/bitwise.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/window.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/vorbisfile.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/vorbisenc.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/synthesis.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/smallft.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/sharedbook.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/res0.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/registry.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/psy.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/mdct.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/mapping0.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/lsp.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/lpc.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/lookup.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/info.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/floor1.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/floor0.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/envelope.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/codebook.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/block.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/bitrate.c \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/analysis.c \
    src/JuceLibraryCode/modules/juce_audio_formats/format/juce_BufferingAudioFormatReader.cpp \
    src/JuceLibraryCode/modules/juce_audio_formats/format/juce_AudioSubsectionReader.cpp \
    src/JuceLibraryCode/modules/juce_audio_formats/format/juce_AudioFormatWriter.cpp \
    src/JuceLibraryCode/modules/juce_audio_formats/format/juce_AudioFormatReaderSource.cpp \
    src/JuceLibraryCode/modules/juce_audio_formats/format/juce_AudioFormatReader.cpp \
    src/JuceLibraryCode/modules/juce_audio_formats/format/juce_AudioFormatManager.cpp \
    src/JuceLibraryCode/modules/juce_audio_formats/format/juce_AudioFormat.cpp \
    src/JuceLibraryCode/modules/juce_audio_formats/sampler/juce_Sampler.cpp \
    src/JuceLibraryCode/modules/juce_core/juce_core.cpp \
    src/JuceLibraryCode/modules/juce_core/containers/juce_Variant.cpp \
    src/JuceLibraryCode/modules/juce_core/containers/juce_PropertySet.cpp \
    src/JuceLibraryCode/modules/juce_core/containers/juce_NamedValueSet.cpp \
    src/JuceLibraryCode/modules/juce_core/containers/juce_DynamicObject.cpp \
    src/JuceLibraryCode/modules/juce_core/containers/juce_AbstractFifo.cpp \
    src/JuceLibraryCode/modules/juce_core/files/juce_TemporaryFile.cpp \
    src/JuceLibraryCode/modules/juce_core/files/juce_FileSearchPath.cpp \
    src/JuceLibraryCode/modules/juce_core/files/juce_FileOutputStream.cpp \
    src/JuceLibraryCode/modules/juce_core/files/juce_FileInputStream.cpp \
    src/JuceLibraryCode/modules/juce_core/files/juce_File.cpp \
    src/JuceLibraryCode/modules/juce_core/files/juce_DirectoryIterator.cpp \
    src/JuceLibraryCode/modules/juce_core/logging/juce_Logger.cpp \
    src/JuceLibraryCode/modules/juce_core/logging/juce_FileLogger.cpp \
    src/JuceLibraryCode/modules/juce_core/maths/juce_Random.cpp \
    src/JuceLibraryCode/modules/juce_core/maths/juce_Expression.cpp \
    src/JuceLibraryCode/modules/juce_core/maths/juce_BigInteger.cpp \
    src/JuceLibraryCode/modules/juce_core/memory/juce_MemoryBlock.cpp \
    src/JuceLibraryCode/modules/juce_core/misc/juce_Uuid.cpp \
    src/JuceLibraryCode/modules/juce_core/misc/juce_Result.cpp \
    src/JuceLibraryCode/modules/juce_core/native/juce_win32_Threads.cpp \
    src/JuceLibraryCode/modules/juce_core/native/juce_win32_SystemStats.cpp \
    src/JuceLibraryCode/modules/juce_core/native/juce_win32_Registry.cpp \
    src/JuceLibraryCode/modules/juce_core/native/juce_win32_Network.cpp \
    src/JuceLibraryCode/modules/juce_core/native/juce_win32_Files.cpp \
    src/JuceLibraryCode/modules/juce_core/native/juce_posix_NamedPipe.cpp \
    src/JuceLibraryCode/modules/juce_core/native/juce_linux_Threads.cpp \
    src/JuceLibraryCode/modules/juce_core/native/juce_linux_SystemStats.cpp \
    src/JuceLibraryCode/modules/juce_core/native/juce_linux_Network.cpp \
    src/JuceLibraryCode/modules/juce_core/native/juce_linux_Files.cpp \
    src/JuceLibraryCode/modules/juce_core/native/juce_android_Threads.cpp \
    src/JuceLibraryCode/modules/juce_core/native/juce_android_SystemStats.cpp \
    src/JuceLibraryCode/modules/juce_core/native/juce_android_Network.cpp \
    src/JuceLibraryCode/modules/juce_core/native/juce_android_Misc.cpp \
    src/JuceLibraryCode/modules/juce_core/native/juce_android_Files.cpp \
    src/JuceLibraryCode/modules/juce_core/network/juce_URL.cpp \
    src/JuceLibraryCode/modules/juce_core/network/juce_Socket.cpp \
    src/JuceLibraryCode/modules/juce_core/network/juce_NamedPipe.cpp \
    src/JuceLibraryCode/modules/juce_core/network/juce_MACAddress.cpp \
    src/JuceLibraryCode/modules/juce_core/network/juce_IPAddress.cpp \
    src/JuceLibraryCode/modules/juce_core/streams/juce_SubregionStream.cpp \
    src/JuceLibraryCode/modules/juce_core/streams/juce_OutputStream.cpp \
    src/JuceLibraryCode/modules/juce_core/streams/juce_MemoryOutputStream.cpp \
    src/JuceLibraryCode/modules/juce_core/streams/juce_MemoryInputStream.cpp \
    src/JuceLibraryCode/modules/juce_core/streams/juce_InputStream.cpp \
    src/JuceLibraryCode/modules/juce_core/streams/juce_FileInputSource.cpp \
    src/JuceLibraryCode/modules/juce_core/streams/juce_BufferedInputStream.cpp \
    src/JuceLibraryCode/modules/juce_core/system/juce_SystemStats.cpp \
    src/JuceLibraryCode/modules/juce_core/text/juce_TextDiff.cpp \
    src/JuceLibraryCode/modules/juce_core/text/juce_StringPool.cpp \
    src/JuceLibraryCode/modules/juce_core/text/juce_StringPairArray.cpp \
    src/JuceLibraryCode/modules/juce_core/text/juce_StringArray.cpp \
    src/JuceLibraryCode/modules/juce_core/text/juce_String.cpp \
    src/JuceLibraryCode/modules/juce_core/text/juce_LocalisedStrings.cpp \
    src/JuceLibraryCode/modules/juce_core/text/juce_Identifier.cpp \
    src/JuceLibraryCode/modules/juce_core/text/juce_CharacterFunctions.cpp \
    src/JuceLibraryCode/modules/juce_core/threads/juce_TimeSliceThread.cpp \
    src/JuceLibraryCode/modules/juce_core/threads/juce_ThreadPool.cpp \
    src/JuceLibraryCode/modules/juce_core/threads/juce_Thread.cpp \
    src/JuceLibraryCode/modules/juce_core/threads/juce_ReadWriteLock.cpp \
    src/JuceLibraryCode/modules/juce_core/threads/juce_HighResolutionTimer.cpp \
    src/JuceLibraryCode/modules/juce_core/threads/juce_ChildProcess.cpp \
    src/JuceLibraryCode/modules/juce_core/time/juce_Time.cpp \
    src/JuceLibraryCode/modules/juce_core/time/juce_RelativeTime.cpp \
    src/JuceLibraryCode/modules/juce_core/time/juce_PerformanceCounter.cpp \
    src/JuceLibraryCode/modules/juce_core/unit_tests/juce_UnitTest.cpp \
    src/JuceLibraryCode/modules/juce_core/xml/juce_XmlElement.cpp \
    src/JuceLibraryCode/modules/juce_core/xml/juce_XmlDocument.cpp \
    src/JuceLibraryCode/modules/juce_core/zip/juce_ZipFile.cpp \
    src/JuceLibraryCode/modules/juce_core/zip/juce_GZIPDecompressorInputStream.cpp \
    src/JuceLibraryCode/modules/juce_core/zip/juce_GZIPCompressorOutputStream.cpp \
    src/JuceLibraryCode/modules/juce_core/javascript/juce_JSON.cpp \
    src/JuceLibraryCode/modules/juce_core/javascript/juce_Javascript.cpp \
    src/JuceLibraryCode/modules/juce_data_structures/juce_data_structures.cpp \
    src/JuceLibraryCode/modules/juce_data_structures/app_properties/juce_PropertiesFile.cpp \
    src/JuceLibraryCode/modules/juce_data_structures/app_properties/juce_ApplicationProperties.cpp \
    src/JuceLibraryCode/modules/juce_data_structures/undomanager/juce_UndoManager.cpp \
    src/JuceLibraryCode/modules/juce_data_structures/values/juce_ValueTree.cpp \
    src/JuceLibraryCode/modules/juce_data_structures/values/juce_Value.cpp \
    src/JuceLibraryCode/modules/juce_events/juce_events.cpp \
    src/JuceLibraryCode/modules/juce_events/broadcasters/juce_ChangeBroadcaster.cpp \
    src/JuceLibraryCode/modules/juce_events/broadcasters/juce_AsyncUpdater.cpp \
    src/JuceLibraryCode/modules/juce_events/broadcasters/juce_ActionBroadcaster.cpp \
    src/JuceLibraryCode/modules/juce_events/interprocess/juce_InterprocessConnectionServer.cpp \
    src/JuceLibraryCode/modules/juce_events/interprocess/juce_InterprocessConnection.cpp \
    src/JuceLibraryCode/modules/juce_events/messages/juce_MessageManager.cpp \
    src/JuceLibraryCode/modules/juce_events/messages/juce_MessageListener.cpp \
    src/JuceLibraryCode/modules/juce_events/messages/juce_DeletedAtShutdown.cpp \
    src/JuceLibraryCode/modules/juce_events/messages/juce_ApplicationBase.cpp \
    src/JuceLibraryCode/modules/juce_events/native/juce_win32_Messaging.cpp \
    src/JuceLibraryCode/modules/juce_events/native/juce_linux_Messaging.cpp \
    src/JuceLibraryCode/modules/juce_events/native/juce_android_Messaging.cpp \
    src/JuceLibraryCode/modules/juce_events/timers/juce_Timer.cpp \
    src/JuceLibraryCode/modules/juce_events/timers/juce_MultiTimer.cpp \
    src/JuceLibraryCode/modules/juce_audio_devices/native/relay_libjack.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/dRowAudio.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_SoundTouchProcessor.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_SoundTouchAudioSource.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_SampleRateConverter.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_ReversibleAudioSource.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_PitchDetector.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_LoopingAudioSource.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_FilteringAudioSource.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_EnvelopeFollower.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_Buffer.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_AudioUtilityUnitTests.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_AudioSampleBufferAudioFormat.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_AudioFilePlayerExt.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_AudioFilePlayer.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/filters/dRowAudio_OnePoleFilter.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/filters/dRowAudio_BiquadFilter.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/TDStretch.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/sse_optimized.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/SoundTouch_Source.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/SoundTouch.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/RateTransposer.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/PeakFinder.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/mmx_optimized.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/FIRFilter.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/FIFOSampleBuffer.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/cpu_detect_x86_win.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/cpu_detect_x86_gcc.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/cpu_detect_x64_win.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/cpu_detect_x64_gcc.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/BPMDetect.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/AAFilter.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/maths/dRowAudio_MathsUnitTests.cpp \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/streams/dRowAudio_MemoryInputSource.cpp \
    src/main.cpp \
    src/mainwindow.cpp \
    src/wavegraphicsview.cpp \
    src/waveformitem.cpp \
    src/audiosetupdialog.cpp \
    src/audiofilehandler.cpp \
    src/sampleraudiosource.cpp \
    src/shurikensampler.cpp \
    src/slicepointitem.cpp \
    src/commands.cpp
HEADERS += src/JuceLibraryCode/JuceHeader.h \
    src/JuceLibraryCode/AppConfig.h \
    src/JuceLibraryCode/modules/juce_audio_basics/juce_audio_basics.h \
    src/JuceLibraryCode/modules/juce_audio_basics/buffers/juce_AudioDataConverters.h \
    src/JuceLibraryCode/modules/juce_audio_basics/buffers/juce_FloatVectorOperations.h \
    src/JuceLibraryCode/modules/juce_audio_basics/buffers/juce_AudioSampleBuffer.h \
    src/JuceLibraryCode/modules/juce_audio_basics/effects/juce_Reverb.h \
    src/JuceLibraryCode/modules/juce_audio_basics/effects/juce_LagrangeInterpolator.h \
    src/JuceLibraryCode/modules/juce_audio_basics/effects/juce_IIRFilter.h \
    src/JuceLibraryCode/modules/juce_audio_basics/effects/juce_Decibels.h \
    src/JuceLibraryCode/modules/juce_audio_basics/midi/juce_MidiMessageSequence.h \
    src/JuceLibraryCode/modules/juce_audio_basics/midi/juce_MidiMessage.h \
    src/JuceLibraryCode/modules/juce_audio_basics/midi/juce_MidiKeyboardState.h \
    src/JuceLibraryCode/modules/juce_audio_basics/midi/juce_MidiFile.h \
    src/JuceLibraryCode/modules/juce_audio_basics/midi/juce_MidiBuffer.h \
    src/JuceLibraryCode/modules/juce_audio_basics/sources/juce_ToneGeneratorAudioSource.h \
    src/JuceLibraryCode/modules/juce_audio_basics/sources/juce_ReverbAudioSource.h \
    src/JuceLibraryCode/modules/juce_audio_basics/sources/juce_ResamplingAudioSource.h \
    src/JuceLibraryCode/modules/juce_audio_basics/sources/juce_PositionableAudioSource.h \
    src/JuceLibraryCode/modules/juce_audio_basics/sources/juce_MixerAudioSource.h \
    src/JuceLibraryCode/modules/juce_audio_basics/sources/juce_IIRFilterAudioSource.h \
    src/JuceLibraryCode/modules/juce_audio_basics/sources/juce_ChannelRemappingAudioSource.h \
    src/JuceLibraryCode/modules/juce_audio_basics/sources/juce_BufferingAudioSource.h \
    src/JuceLibraryCode/modules/juce_audio_basics/sources/juce_AudioSource.h \
    src/JuceLibraryCode/modules/juce_audio_basics/synthesisers/juce_Synthesiser.h \
    src/JuceLibraryCode/modules/juce_audio_devices/juce_audio_devices.h \
    src/JuceLibraryCode/modules/juce_audio_devices/audio_cd/juce_AudioCDReader.h \
    src/JuceLibraryCode/modules/juce_audio_devices/audio_cd/juce_AudioCDBurner.h \
    src/JuceLibraryCode/modules/juce_audio_devices/audio_io/juce_SystemAudioVolume.h \
    src/JuceLibraryCode/modules/juce_audio_devices/audio_io/juce_AudioIODeviceType.h \
    src/JuceLibraryCode/modules/juce_audio_devices/audio_io/juce_AudioIODevice.h \
    src/JuceLibraryCode/modules/juce_audio_devices/audio_io/juce_AudioDeviceManager.h \
    src/JuceLibraryCode/modules/juce_audio_devices/midi_io/juce_MidiOutput.h \
    src/JuceLibraryCode/modules/juce_audio_devices/midi_io/juce_MidiMessageCollector.h \
    src/JuceLibraryCode/modules/juce_audio_devices/midi_io/juce_MidiInput.h \
    src/JuceLibraryCode/modules/juce_audio_devices/native/juce_MidiDataConcatenator.h \
    src/JuceLibraryCode/modules/juce_audio_devices/sources/juce_AudioTransportSource.h \
    src/JuceLibraryCode/modules/juce_audio_devices/sources/juce_AudioSourcePlayer.h \
    src/JuceLibraryCode/modules/juce_audio_formats/juce_audio_formats.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/juce_WindowsMediaAudioFormat.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/juce_WavAudioFormat.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/juce_QuickTimeAudioFormat.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/juce_OggVorbisAudioFormat.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/juce_MP3AudioFormat.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/juce_LAMEEncoderAudioFormat.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/juce_FlacAudioFormat.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/juce_CoreAudioFormat.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/juce_AiffAudioFormat.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/stream_encoder.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/stream_decoder.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/ordinals.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/metadata.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/format.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/export.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/callback.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/assert.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/alloc.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/all.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/vorbisfile.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/vorbisenc.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/os_types.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/ogg.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/config_types.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/codec.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/window.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/smallft.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/scales.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/registry.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/psy.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/os.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/misc.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/mdct.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/masking.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/lsp.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/lpc.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/lookup_data.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/lookup.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/highlevel.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/envelope.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/codec_internal.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/codebook.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/bitrate.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/backends.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/books/coupled/res_books_stereo.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/books/coupled/res_books_51.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/books/floor/floor_books.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/books/uncoupled/res_books_uncoupled.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/setup_X.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/setup_44u.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/setup_44p51.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/setup_44.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/setup_32.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/setup_22.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/setup_16.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/setup_11.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/setup_8.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/residue_44u.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/residue_44p51.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/residue_44.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/residue_16.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/residue_8.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/psych_44.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/psych_16.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/psych_11.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/psych_8.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/lib/modes/floor_all.h \
    src/JuceLibraryCode/modules/juce_audio_formats/format/juce_MemoryMappedAudioFormatReader.h \
    src/JuceLibraryCode/modules/juce_audio_formats/format/juce_BufferingAudioFormatReader.h \
    src/JuceLibraryCode/modules/juce_audio_formats/format/juce_AudioSubsectionReader.h \
    src/JuceLibraryCode/modules/juce_audio_formats/format/juce_AudioFormatWriter.h \
    src/JuceLibraryCode/modules/juce_audio_formats/format/juce_AudioFormatReaderSource.h \
    src/JuceLibraryCode/modules/juce_audio_formats/format/juce_AudioFormatReader.h \
    src/JuceLibraryCode/modules/juce_audio_formats/format/juce_AudioFormatManager.h \
    src/JuceLibraryCode/modules/juce_audio_formats/format/juce_AudioFormat.h \
    src/JuceLibraryCode/modules/juce_audio_formats/sampler/juce_Sampler.h \
    src/JuceLibraryCode/modules/juce_core/juce_core.h \
    src/JuceLibraryCode/modules/juce_core/containers/juce_Variant.h \
    src/JuceLibraryCode/modules/juce_core/containers/juce_SparseSet.h \
    src/JuceLibraryCode/modules/juce_core/containers/juce_SortedSet.h \
    src/JuceLibraryCode/modules/juce_core/containers/juce_ScopedValueSetter.h \
    src/JuceLibraryCode/modules/juce_core/containers/juce_ReferenceCountedArray.h \
    src/JuceLibraryCode/modules/juce_core/containers/juce_PropertySet.h \
    src/JuceLibraryCode/modules/juce_core/containers/juce_OwnedArray.h \
    src/JuceLibraryCode/modules/juce_core/containers/juce_NamedValueSet.h \
    src/JuceLibraryCode/modules/juce_core/containers/juce_LinkedListPointer.h \
    src/JuceLibraryCode/modules/juce_core/containers/juce_HashMap.h \
    src/JuceLibraryCode/modules/juce_core/containers/juce_ElementComparator.h \
    src/JuceLibraryCode/modules/juce_core/containers/juce_DynamicObject.h \
    src/JuceLibraryCode/modules/juce_core/containers/juce_ArrayAllocationBase.h \
    src/JuceLibraryCode/modules/juce_core/containers/juce_Array.h \
    src/JuceLibraryCode/modules/juce_core/containers/juce_AbstractFifo.h \
    src/JuceLibraryCode/modules/juce_core/files/juce_TemporaryFile.h \
    src/JuceLibraryCode/modules/juce_core/files/juce_MemoryMappedFile.h \
    src/JuceLibraryCode/modules/juce_core/files/juce_FileSearchPath.h \
    src/JuceLibraryCode/modules/juce_core/files/juce_FileOutputStream.h \
    src/JuceLibraryCode/modules/juce_core/files/juce_FileInputStream.h \
    src/JuceLibraryCode/modules/juce_core/files/juce_File.h \
    src/JuceLibraryCode/modules/juce_core/files/juce_DirectoryIterator.h \
    src/JuceLibraryCode/modules/juce_core/logging/juce_Logger.h \
    src/JuceLibraryCode/modules/juce_core/logging/juce_FileLogger.h \
    src/JuceLibraryCode/modules/juce_core/maths/juce_Range.h \
    src/JuceLibraryCode/modules/juce_core/maths/juce_Random.h \
    src/JuceLibraryCode/modules/juce_core/maths/juce_MathsFunctions.h \
    src/JuceLibraryCode/modules/juce_core/maths/juce_Expression.h \
    src/JuceLibraryCode/modules/juce_core/maths/juce_BigInteger.h \
    src/JuceLibraryCode/modules/juce_core/memory/juce_WeakReference.h \
    src/JuceLibraryCode/modules/juce_core/memory/juce_Singleton.h \
    src/JuceLibraryCode/modules/juce_core/memory/juce_ScopedPointer.h \
    src/JuceLibraryCode/modules/juce_core/memory/juce_ReferenceCountedObject.h \
    src/JuceLibraryCode/modules/juce_core/memory/juce_OptionalScopedPointer.h \
    src/JuceLibraryCode/modules/juce_core/memory/juce_MemoryBlock.h \
    src/JuceLibraryCode/modules/juce_core/memory/juce_Memory.h \
    src/JuceLibraryCode/modules/juce_core/memory/juce_LeakedObjectDetector.h \
    src/JuceLibraryCode/modules/juce_core/memory/juce_HeapBlock.h \
    src/JuceLibraryCode/modules/juce_core/memory/juce_ByteOrder.h \
    src/JuceLibraryCode/modules/juce_core/memory/juce_Atomic.h \
    src/JuceLibraryCode/modules/juce_core/misc/juce_WindowsRegistry.h \
    src/JuceLibraryCode/modules/juce_core/misc/juce_Uuid.h \
    src/JuceLibraryCode/modules/juce_core/misc/juce_Result.h \
    src/JuceLibraryCode/modules/juce_core/native/juce_win32_ComSmartPtr.h \
    src/JuceLibraryCode/modules/juce_core/native/juce_posix_SharedCode.h \
    src/JuceLibraryCode/modules/juce_core/native/juce_osx_ObjCHelpers.h \
    src/JuceLibraryCode/modules/juce_core/native/juce_BasicNativeHeaders.h \
    src/JuceLibraryCode/modules/juce_core/native/juce_android_JNIHelpers.h \
    src/JuceLibraryCode/modules/juce_core/network/juce_URL.h \
    src/JuceLibraryCode/modules/juce_core/network/juce_Socket.h \
    src/JuceLibraryCode/modules/juce_core/network/juce_NamedPipe.h \
    src/JuceLibraryCode/modules/juce_core/network/juce_MACAddress.h \
    src/JuceLibraryCode/modules/juce_core/network/juce_IPAddress.h \
    src/JuceLibraryCode/modules/juce_core/streams/juce_SubregionStream.h \
    src/JuceLibraryCode/modules/juce_core/streams/juce_OutputStream.h \
    src/JuceLibraryCode/modules/juce_core/streams/juce_MemoryOutputStream.h \
    src/JuceLibraryCode/modules/juce_core/streams/juce_MemoryInputStream.h \
    src/JuceLibraryCode/modules/juce_core/streams/juce_InputStream.h \
    src/JuceLibraryCode/modules/juce_core/streams/juce_InputSource.h \
    src/JuceLibraryCode/modules/juce_core/streams/juce_FileInputSource.h \
    src/JuceLibraryCode/modules/juce_core/streams/juce_BufferedInputStream.h \
    src/JuceLibraryCode/modules/juce_core/system/juce_TargetPlatform.h \
    src/JuceLibraryCode/modules/juce_core/system/juce_SystemStats.h \
    src/JuceLibraryCode/modules/juce_core/system/juce_StandardHeader.h \
    src/JuceLibraryCode/modules/juce_core/system/juce_PlatformDefs.h \
    src/JuceLibraryCode/modules/juce_core/text/juce_TextDiff.h \
    src/JuceLibraryCode/modules/juce_core/text/juce_StringPool.h \
    src/JuceLibraryCode/modules/juce_core/text/juce_StringPairArray.h \
    src/JuceLibraryCode/modules/juce_core/text/juce_StringArray.h \
    src/JuceLibraryCode/modules/juce_core/text/juce_String.h \
    src/JuceLibraryCode/modules/juce_core/text/juce_NewLine.h \
    src/JuceLibraryCode/modules/juce_core/text/juce_LocalisedStrings.h \
    src/JuceLibraryCode/modules/juce_core/text/juce_Identifier.h \
    src/JuceLibraryCode/modules/juce_core/text/juce_CharPointer_UTF32.h \
    src/JuceLibraryCode/modules/juce_core/text/juce_CharPointer_UTF16.h \
    src/JuceLibraryCode/modules/juce_core/text/juce_CharPointer_UTF8.h \
    src/JuceLibraryCode/modules/juce_core/text/juce_CharPointer_ASCII.h \
    src/JuceLibraryCode/modules/juce_core/text/juce_CharacterFunctions.h \
    src/JuceLibraryCode/modules/juce_core/threads/juce_WaitableEvent.h \
    src/JuceLibraryCode/modules/juce_core/threads/juce_TimeSliceThread.h \
    src/JuceLibraryCode/modules/juce_core/threads/juce_ThreadPool.h \
    src/JuceLibraryCode/modules/juce_core/threads/juce_ThreadLocalValue.h \
    src/JuceLibraryCode/modules/juce_core/threads/juce_Thread.h \
    src/JuceLibraryCode/modules/juce_core/threads/juce_SpinLock.h \
    src/JuceLibraryCode/modules/juce_core/threads/juce_ScopedWriteLock.h \
    src/JuceLibraryCode/modules/juce_core/threads/juce_ScopedReadLock.h \
    src/JuceLibraryCode/modules/juce_core/threads/juce_ScopedLock.h \
    src/JuceLibraryCode/modules/juce_core/threads/juce_ReadWriteLock.h \
    src/JuceLibraryCode/modules/juce_core/threads/juce_Process.h \
    src/JuceLibraryCode/modules/juce_core/threads/juce_InterProcessLock.h \
    src/JuceLibraryCode/modules/juce_core/threads/juce_HighResolutionTimer.h \
    src/JuceLibraryCode/modules/juce_core/threads/juce_DynamicLibrary.h \
    src/JuceLibraryCode/modules/juce_core/threads/juce_CriticalSection.h \
    src/JuceLibraryCode/modules/juce_core/threads/juce_ChildProcess.h \
    src/JuceLibraryCode/modules/juce_core/time/juce_Time.h \
    src/JuceLibraryCode/modules/juce_core/time/juce_RelativeTime.h \
    src/JuceLibraryCode/modules/juce_core/time/juce_PerformanceCounter.h \
    src/JuceLibraryCode/modules/juce_core/unit_tests/juce_UnitTest.h \
    src/JuceLibraryCode/modules/juce_core/xml/juce_XmlElement.h \
    src/JuceLibraryCode/modules/juce_core/xml/juce_XmlDocument.h \
    src/JuceLibraryCode/modules/juce_core/zip/juce_ZipFile.h \
    src/JuceLibraryCode/modules/juce_core/zip/juce_GZIPDecompressorInputStream.h \
    src/JuceLibraryCode/modules/juce_core/zip/juce_GZIPCompressorOutputStream.h \
    src/JuceLibraryCode/modules/juce_core/zip/zlib/zutil.h \
    src/JuceLibraryCode/modules/juce_core/zip/zlib/zlib.h \
    src/JuceLibraryCode/modules/juce_core/zip/zlib/zconf.in.h \
    src/JuceLibraryCode/modules/juce_core/zip/zlib/zconf.h \
    src/JuceLibraryCode/modules/juce_core/zip/zlib/trees.h \
    src/JuceLibraryCode/modules/juce_core/zip/zlib/inftrees.h \
    src/JuceLibraryCode/modules/juce_core/zip/zlib/inflate.h \
    src/JuceLibraryCode/modules/juce_core/zip/zlib/inffixed.h \
    src/JuceLibraryCode/modules/juce_core/zip/zlib/inffast.h \
    src/JuceLibraryCode/modules/juce_core/zip/zlib/deflate.h \
    src/JuceLibraryCode/modules/juce_core/zip/zlib/crc32.h \
    src/JuceLibraryCode/modules/juce_core/javascript/juce_JSON.h \
    src/JuceLibraryCode/modules/juce_core/javascript/juce_Javascript.h \
    src/JuceLibraryCode/modules/juce_audio_devices/native/linux_midi.h \
    src/JuceLibraryCode/modules/juce_data_structures/juce_data_structures.h \
    src/JuceLibraryCode/modules/juce_data_structures/app_properties/juce_PropertiesFile.h \
    src/JuceLibraryCode/modules/juce_data_structures/app_properties/juce_ApplicationProperties.h \
    src/JuceLibraryCode/modules/juce_data_structures/undomanager/juce_UndoManager.h \
    src/JuceLibraryCode/modules/juce_data_structures/undomanager/juce_UndoableAction.h \
    src/JuceLibraryCode/modules/juce_data_structures/values/juce_ValueTree.h \
    src/JuceLibraryCode/modules/juce_data_structures/values/juce_Value.h \
    src/JuceLibraryCode/modules/juce_events/juce_events.h \
    src/JuceLibraryCode/modules/juce_events/broadcasters/juce_ListenerList.h \
    src/JuceLibraryCode/modules/juce_events/broadcasters/juce_ChangeListener.h \
    src/JuceLibraryCode/modules/juce_events/broadcasters/juce_ChangeBroadcaster.h \
    src/JuceLibraryCode/modules/juce_events/broadcasters/juce_AsyncUpdater.h \
    src/JuceLibraryCode/modules/juce_events/broadcasters/juce_ActionListener.h \
    src/JuceLibraryCode/modules/juce_events/broadcasters/juce_ActionBroadcaster.h \
    src/JuceLibraryCode/modules/juce_events/interprocess/juce_InterprocessConnectionServer.h \
    src/JuceLibraryCode/modules/juce_events/interprocess/juce_InterprocessConnection.h \
    src/JuceLibraryCode/modules/juce_events/messages/juce_NotificationType.h \
    src/JuceLibraryCode/modules/juce_events/messages/juce_MessageManager.h \
    src/JuceLibraryCode/modules/juce_events/messages/juce_MessageListener.h \
    src/JuceLibraryCode/modules/juce_events/messages/juce_Message.h \
    src/JuceLibraryCode/modules/juce_events/messages/juce_DeletedAtShutdown.h \
    src/JuceLibraryCode/modules/juce_events/messages/juce_CallbackMessage.h \
    src/JuceLibraryCode/modules/juce_events/messages/juce_ApplicationBase.h \
    src/JuceLibraryCode/modules/juce_events/native/juce_win32_HiddenMessageWindow.h \
    src/JuceLibraryCode/modules/juce_events/native/juce_ScopedXLock.h \
    src/JuceLibraryCode/modules/juce_events/native/juce_osx_MessageQueue.h \
    src/JuceLibraryCode/modules/juce_events/timers/juce_Timer.h \
    src/JuceLibraryCode/modules/juce_events/timers/juce_MultiTimer.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/window.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/stream_encoder_framing.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/metadata.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/memory.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/md5.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/lpc.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/format.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/float.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/fixed.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/crc.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/cpu.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/bitwriter.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/bitreader.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/bitmath.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/include/private/all.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/include/protected/stream_encoder.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/include/protected/stream_decoder.h \
    src/JuceLibraryCode/modules/juce_audio_formats/codecs/flac/libFLAC/include/protected/all.h \
    src/JuceLibraryCode/modules/juce_audio_devices/native/jack_device.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/dRowAudio.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_SoundTouchProcessor.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_SoundTouchAudioSource.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_SampleRateConverter.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_ReversibleAudioSource.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_PitchDetector.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_Pitch.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_LoopingAudioSource.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_FilteringAudioSource.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_FifoBuffer.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_EnvelopeFollower.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_Buffer.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_AudioUtility.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_AudioSampleBufferAudioFormat.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_AudioFilePlayerExt.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/dRowAudio_AudioFilePlayer.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/filters/dRowAudio_OnePoleFilter.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/filters/dRowAudio_BiquadFilter.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/TDStretch.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/STTypes.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/SoundTouch_Includes.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/soundtouch_config.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/SoundTouch.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/RateTransposer.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/PeakFinder.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/FIRFilter.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/FIFOSamplePipe.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/FIFOSampleBuffer.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/cpu_detect.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/BPMDetect.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/audio/soundtouch/AAFilter.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/maths/dRowAudio_MathsUtilities.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/maths/dRowAudio_CumulativeMovingAverage.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/maths/dRowAudio_BezierCurve.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/streams/dRowAudio_MemoryInputSource.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/utility/dRowAudio_Utility.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/utility/dRowAudio_XmlHelpers.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/utility/dRowAudio_DebugObject.h \
    src/JuceLibraryCode/modules/drowaudio/dRowAudio/utility/dRowAudio_Constants.h \
    src/mainwindow.h \
    src/wavegraphicsview.h \
    src/waveformitem.h \
    src/audiosetupdialog.h \
    src/audiofilehandler.h \
    src/samplebuffer.h \
    src/sampleraudiosource.h \
    src/shurikensampler.h \
    src/slicepointitem.h \
    src/commands.h \
    src/simplesynth.h
FORMS += src/mainwindow.ui \
    src/audiosetupdialog.ui
INCLUDEPATH += src \
    src/SndLibShuriken \
    src/JuceLibraryCode \
    usr/include/aubio
LIBS += -Llib \
    -lsndlib_shuriken \
    -laubio \
    -L/usr/X11R6/lib \
    -lX11 \
    -lasound \
    -ldl \
    -lpthread \
    -lrt
unix:DEFINES += "LINUX=1"
CONFIG(debug, debug|release) { 
    DESTDIR = $$OUT_PWD/debug
    DEFINES += "DEBUG=1" \
        "_DEBUG=1"
}
else { 
    DESTDIR = $$OUT_PWD
    DEFINES += "NDEBUG=1"
}
OBJECTS_DIR = $${DESTDIR}/.obj
MOC_DIR = $${DESTDIR}/.moc
RCC_DIR = $${DESTDIR}/.rcc
UI_DIR = $${DESTDIR}/.ui
