#! /bin/sh

# borrowed from gsl-config.in

prefix=/usr/local
exec_prefix=${prefix}
includedir=${prefix}/include

usage()
{
    cat <<EOF
Usage: sndlib-config [OPTION]

Known values for OPTION are:

  --prefix		show Sndlib installation prefix 
  --libs		print library linking information
  --cflags		print pre-processor and compiler flags
  --help		display this help and exit
  --version		output version information
  --language            extension language info
  --audio               audio library choice

EOF

    exit $1
}

if test $# -eq 0; then
    usage 1
fi

cflags=false
libs=false

while test $# -gt 0; do
    case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
    esac

    case "$1" in
    --prefix=*)
	prefix=$optarg
	;;

    --prefix)
	echo $prefix
	;;

    --version)
	echo 22
	exit 0
	;;

    --help)
	usage 0
	;;

    --cflags)
       	echo -I. -g -O2   
       	;;

    --libs)
       	echo  -lm -ldl     -lm
       	;;

    --language)
	echo None
	;;

    --audio)
	echo None
	;;

    *)
	usage
	exit 1
	;;
    esac
    shift
done

exit 0
